mapa = [
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "ppppp                              ppppp",
    "ppppp                              ppppp",
    "ppppp                              ppppp",
    "ppppp                              ppppp",
    "ppppp                              ppppp",
    "ppppp                              ppppp",
    "ppppp                              ppppp",
    "ppppp                              ppppp",
    "ppppp                              ppppp",
    "ppppp                              ppppp",
    "ppppp                              ppppp",
    "ppppp                              ppppp",
    "ppppp                              ppppp",
    "ppppp                              ppppp",
    "ppppp                              ppppp",

]
