mapa = [
    "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
    "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
    "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
    "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
    "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
    "ppppp                              ppppp",
    "ppppp                              ppppp",
    "ppppp                              ppppp",
    "ppppp                              ppppp",
    "ppppp                              ppppp",
    "ppppp                              ppppp",
    "ppppp                              ppppp",
    "ppppp                              ppppp",
    "ppppp                              ppppp",
    "ppppp                              ppppp",
    "ppppp                              ppppp",
    "ppppp                              ppppp",
    "ppppp                              ppppp",
    "ppppp                              ppppp",
    "ppppp                              ppppp",

]
